version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boutique
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
